---
version: '3.4'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ES_CLUSTER_NAME: "docker-cluster"
      ES_NETWORK_HOST: 0.0.0.0
      ES_DISCOVERY_ZEN_MINIMUM_MASTER_NODES: 1
      ES_DISCOVERY_TYPE: single-node
    networks:
      - elk
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.3
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000/udp"
      - "5514:5514"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LS_HTTP_HOST: "0.0.0.0"
      LS_PATH_CONFIG: /usr/share/logstash/pipeline
    networks:
      - elk
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  elk: {}
